### ISSUE TITLE
Device temperature set point display and up/down controls not working

### ISSUE THREAD

**Issue by carcola** [toggledbits/IntesisWMPGateway#1]
I recently installed and configured the Intesis TO-RC-WMP-1 interface. I have installed and configured the plugin. I created the ForceUnits variable but the device temperature set point UI doesn't display degC. It initially displays degC but when attempting to adjust the set point it changes to degF. The up/down control arrow buttons do not work. 

I would appreciate help please. Thanks Carmine
![image](https://user-images.githubusercontent.com/46208740/50502202-95c95680-0ab1-11e9-8fc3-f0848b0b78a2.png)
![image](https://user-images.githubusercontent.com/46208740/50502225-b2658e80-0ab1-11e9-80d7-b92cca456d21.png)

**Comment by toggledbits** [comment]
Vera broke the buttons sometime around firmware 1.7.23. They are aware of the problem but with the recent acquisition and priorities being determined by bigger needs, there's no ETA from them on when this would be fixed. The buttons work slightly differently in the dashboard card vs the control panel, with the latter being more reliable, so make sure you are in the control panel when attempting to adjust temperature. Also, make sure you do a full cache-flush and reload of your browser (CTRL-F5 on Chrome/Windows, Shift-F5 on Firefox/Windows, etc.), as changing the units changes the UI, and you need to force reload the new data.

**Comment by carcola** [comment]
Thank you very much. 
Btw, I'm using ImperiHome - is this a better option to control the interface? 

I followed your instructions but I haven't been able to set it up because i do not have "ImperiHome Standard System" as an option to select when adding an object. Would you know why this is?

**Comment by toggledbits** [comment]
I just checked and "ImperiHome Standard System" is listed as an addable object type in my app (Android). If you're not seeing it, I'd contact their support/community.

**Comment by carcola** [comment]
Thanks I'll contact support,
